query GetClients{
  getClients{
    firstName
    lastName
    phoneNumber
    email
    gender
  }
}

mutation CreateClient($CreateClientInput: CreateClientInput!){
  createClient(createClientInput:$CreateClientInput){
    id
    firstName
    lastName
    phoneNumber
    email
    gender
  }
}