query GetSellers{
  getSellers{
    id
    firstName
    lastName
    phoneNumber
    email
    gender
  }
}

mutation CreateSeller($CreateSellerInput: CreateSellerInput!){
  createSeller(createSellerInput: $CreateSellerInput){
    id
    firstName
  }
}