query GetDrones{
  getDrones{
    name
    subtitle
    description
    price
    stock
    imageUrl
  }
}

query GetDrone($droneName: String!) {
  getDrone(name: $droneName) {
    name
    subtitle
    description
    price
    stock
    imageUrl
  }
}

mutation CreateDrone($CreateDrone: CreateDroneInput!){
  createDrone(createDroneInput: $CreateDrone){
    name
  	description
  }
}

